# Generated by Django 4.0.6 on 2023-03-02 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ottratings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web',
            name='landscape',
        ),
        migrations.RemoveField(
            model_name='web',
            name='portrait',
        ),
    ]
